version: "3.3"
services:
  agent:
    image: grafana/agent:v0.39.1
    network_mode: host
    pid: host
    cap_add:
      - SYS_TIME
    volumes:
      # System Info
      - /:/host/root:ro
      - /sys:/host/sys:ro
      - /proc:/host/proc:ro
      # Logs
      - /var/log:/var/host-log
      # Agent Data store
      - ./volumes/grafana-agent/config:/etc/agent/data
      # Agent configuration
      - ./agent.yaml:/etc/agent/agent.yaml
networks: {}
